In [ ]:
import boto3
import json
import pandas as pd
import io

s3 = boto3.client("s3")
BUCKET = "yankees-pipeline-andre"

## Hitters

In [ ]:
# grab one file to start
test_hitter_key = "raw/game_logs/2026-06-02/player_680474_hitting.json"
obj = s3.get_object(Bucket=BUCKET, Key=test_hitter_key)
data = json.loads(obj["Body"].read())

In [2]:
splits = data['stats'][0]['splits']
df = pd.json_normalize(splits)
df.columns

Index(['season', 'date', 'gameType', 'isHome', 'isWin', 'positionsPlayed',
       'stat.summary', 'stat.gamesPlayed', 'stat.flyOuts', 'stat.groundOuts',
       'stat.airOuts', 'stat.runs', 'stat.doubles', 'stat.triples',
       'stat.homeRuns', 'stat.strikeOuts', 'stat.baseOnBalls',
       'stat.intentionalWalks', 'stat.hits', 'stat.hitByPitch', 'stat.avg',
       'stat.atBats', 'stat.obp', 'stat.slg', 'stat.ops',
       'stat.caughtStealing', 'stat.stolenBases', 'stat.stolenBasePercentage',
       'stat.caughtStealingPercentage', 'stat.groundIntoDoublePlay',
       'stat.groundIntoTriplePlay', 'stat.numberOfPitches',
       'stat.plateAppearances', 'stat.totalBases', 'stat.rbi',
       'stat.leftOnBase', 'stat.sacBunts', 'stat.sacFlies', 'stat.babip',
       'stat.groundOutsToAirouts', 'stat.catchersInterference',
       'stat.atBatsPerHomeRun', 'team.id', 'team.name', 'team.link',
       'player.id', 'player.fullName', 'player.link', 'league.id',
       'league.name', 'league.link', 'sport.id', 'sport.link',
       'sport.abbreviation', 'opponent.id', 'opponent.name', 'opponent.link',
       'game.gamePk', 'game.link', 'game.content.link', 'game.gameNumber',
       'game.dayNight'],
      dtype='str')

In [3]:
pd.set_option('display.max_columns', None)
df.head(1)

,season,date,gameType,isHome,isWin,positionsPlayed,stat.summary,stat.gamesPlayed,stat.flyOuts,stat.groundOuts,stat.airOuts,stat.runs,stat.doubles,stat.triples,stat.homeRuns,stat.strikeOuts,stat.baseOnBalls,stat.intentionalWalks,stat.hits,stat.hitByPitch,stat.avg,stat.atBats,stat.obp,stat.slg,stat.ops,stat.caughtStealing,stat.stolenBases,stat.stolenBasePercentage,stat.caughtStealingPercentage,stat.groundIntoDoublePlay,stat.groundIntoTriplePlay,stat.numberOfPitches,stat.plateAppearances,stat.totalBases,stat.rbi,stat.leftOnBase,stat.sacBunts,stat.sacFlies,stat.babip,stat.groundOutsToAirouts,stat.catchersInterference,stat.atBatsPerHomeRun,team.id,team.name,team.link,player.id,player.fullName,player.link,league.id,league.name,league.link,sport.id,sport.link,sport.abbreviation,opponent.id,opponent.name,opponent.link,game.gamePk,game.link,game.content.link,game.gameNumber,game.dayNight
0,2026,2026-04-29,R,False,False,"[{'code': '7', 'name': 'Outfielder', 'type': '...",0-1 | BB,1,0,0,1,0,0,0,0,0,1,0,0,0,.000,1,.500,.000,.500,0,0,.---,.---,0,0,13,2,0,0,0,0,0,.000,0.00,0,-.--,147,New York Yankees,/api/v1/teams/147,680474,Max Schuemann,/api/v1/people/680474,103,American League,/api/v1/league/103,1,/api/v1/sports/1,MLB,140,Texas Rangers,/api/v1/teams/140,822907,/api/v1.1/game/822907/feed/live,/api/v1/game/822907/content,1,day

In [4]:
cols = [
    # identity / keys
    'player.id', 'player.fullName', 'game.gamePk', 'date', 'season',
    # dimensions
    'sport.id', 'sport.abbreviation', 'league.id', 'league.name',
    'team.id', 'team.name', 'opponent.id', 'opponent.name',
    'gameType', 'isHome', 'game.dayNight', 'positionsPlayed',
    # stats
    'stat.runs', 'stat.hits', 'stat.doubles', 'stat.triples', 'stat.homeRuns',
    'stat.rbi', 'stat.totalBases', 'stat.baseOnBalls', 'stat.intentionalWalks',
    'stat.strikeOuts', 'stat.hitByPitch', 'stat.atBats', 'stat.plateAppearances',
    'stat.stolenBases', 'stat.caughtStealing', 'stat.groundIntoDoublePlay',
    'stat.numberOfPitches', 'stat.leftOnBase', 'stat.sacBunts', 'stat.sacFlies',
]

df = df[cols]
df.head()

,player.id,player.fullName,game.gamePk,date,season,sport.id,sport.abbreviation,league.id,league.name,team.id,team.name,opponent.id,opponent.name,gameType,isHome,game.dayNight,positionsPlayed,stat.runs,stat.hits,stat.doubles,stat.triples,stat.homeRuns,stat.rbi,stat.totalBases,stat.baseOnBalls,stat.intentionalWalks,stat.strikeOuts,stat.hitByPitch,stat.atBats,stat.plateAppearances,stat.stolenBases,stat.caughtStealing,stat.groundIntoDoublePlay,stat.numberOfPitches,stat.leftOnBase,stat.sacBunts,stat.sacFlies
0,680474,Max Schuemann,822907,2026-04-29,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,False,day,"[{'code': '7', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,13,0,0,0
1,680474,Max Schuemann,823555,2026-05-03,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,"[{'code': '9', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,680474,Max Schuemann,823552,2026-05-04,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,"[{'code': '9', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,680474,Max Schuemann,823551,2026-05-07,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,True,day,"[{'code': '6', 'name': 'Shortstop', 'type': 'I...",0,1,1,0,0,1,2,0,0,1,0,4,4,0,0,0,16,4,0,0
4,680474,Max Schuemann,823792,2026-05-09,2026,1,MLB,103,American League,147,New York Yankees,158,Milwaukee Brewers,R,False,day,"[{'code': '12', 'name': 'Pinch Runner', 'type'...",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
mapped_cols = {
    'player.id': 'player_id',
    'player.fullName': 'player_name',
    'game.gamePk': 'game_pk',
    'date': 'game_date',
    'sport.id': 'sport_id',
    'sport.abbreviation': 'level',
    'league.id': 'league_id',
    'league.name': 'league_name',
    'team.id': 'team_id',
    'team.name': 'team_name',
    'opponent.id': 'opponent_id',
    'opponent.name': 'opponent_name',
    'gameType': 'game_type',
    'isHome': 'is_home',
    'game.dayNight': 'day_night',
    'positionsPlayed': 'positions_played',
    'stat.runs': 'r',
    'stat.hits': 'h',
    'stat.doubles': 'x2b',
    'stat.triples': 'x3b',
    'stat.homeRuns': 'hr',
    'stat.rbi': 'rbi',
    'stat.totalBases': 'tb',
    'stat.baseOnBalls': 'bb',
    'stat.intentionalWalks': 'ibb',
    'stat.strikeOuts': 'so',
    'stat.hitByPitch': 'hbp',
    'stat.atBats': 'ab',
    'stat.plateAppearances': 'pa',
    'stat.stolenBases': 'sb',
    'stat.caughtStealing': 'cs',
    'stat.groundIntoDoublePlay': 'gidp',
    'stat.numberOfPitches': 'np',
    'stat.leftOnBase': 'lob',
    'stat.sacBunts': 'sh',
    'stat.sacFlies': 'sf',
}

df = df.rename(columns=mapped_cols)
df.head()

,player_id,player_name,game_pk,game_date,season,sport_id,level,league_id,league_name,team_id,team_name,opponent_id,opponent_name,game_type,is_home,day_night,positions_played,r,h,x2b,x3b,hr,rbi,tb,bb,ibb,so,hbp,ab,pa,sb,cs,gidp,np,lob,sh,sf
0,680474,Max Schuemann,822907,2026-04-29,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,False,day,"[{'code': '7', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,13,0,0,0
1,680474,Max Schuemann,823555,2026-05-03,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,"[{'code': '9', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,680474,Max Schuemann,823552,2026-05-04,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,"[{'code': '9', 'name': 'Outfielder', 'type': '...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,680474,Max Schuemann,823551,2026-05-07,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,True,day,"[{'code': '6', 'name': 'Shortstop', 'type': 'I...",0,1,1,0,0,1,2,0,0,1,0,4,4,0,0,0,16,4,0,0
4,680474,Max Schuemann,823792,2026-05-09,2026,1,MLB,103,American League,147,New York Yankees,158,Milwaukee Brewers,R,False,day,"[{'code': '12', 'name': 'Pinch Runner', 'type'...",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
df['positions_played'] = df['positions_played'].apply(lambda lst: ','.join(p['abbreviation'] for p in lst) if lst else '')
df['positions_played'][0]

'LF'

In [7]:
df['game_date'] = pd.to_datetime(df['game_date'], format='%Y-%m-%d')
df['game_date'].dtype

dtype('<M8[us]')

In [8]:
df.head()

,player_id,player_name,game_pk,game_date,season,sport_id,level,league_id,league_name,team_id,team_name,opponent_id,opponent_name,game_type,is_home,day_night,positions_played,r,h,x2b,x3b,hr,rbi,tb,bb,ibb,so,hbp,ab,pa,sb,cs,gidp,np,lob,sh,sf
0,680474,Max Schuemann,822907,2026-04-29,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,False,day,LF,0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,13,0,0,0
1,680474,Max Schuemann,823555,2026-05-03,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,RF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,680474,Max Schuemann,823552,2026-05-04,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,RF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,680474,Max Schuemann,823551,2026-05-07,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,True,day,"SS,RF",0,1,1,0,0,1,2,0,0,1,0,4,4,0,0,0,16,4,0,0
4,680474,Max Schuemann,823792,2026-05-09,2026,1,MLB,103,American League,147,New York Yankees,158,Milwaukee Brewers,R,False,day,"PR,LF",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
df.dtypes

player_id                    int64
player_name                    str
game_pk                      int64
game_date           datetime64[us]
season                         str
sport_id                     int64
level                          str
league_id                    int64
league_name                    str
team_id                      int64
team_name                      str
opponent_id                  int64
opponent_name                  str
game_type                      str
is_home                       bool
day_night                      str
positions_played               str
r                            int64
h                            int64
x2b                          int64
x3b                          int64
hr                           int64
rbi                          int64
tb                           int64
bb                           int64
ibb                          int64
so                           int64
hbp                          int64
ab                           int64
pa                           int64
sb                           int64
cs                           int64
gidp                         int64
np                           int64
lob                          int64
sh                           int64
sf                           int64
dtype: object

In [10]:
df['season'] = df['season'].astype(int)

In [11]:
df.head()

,player_id,player_name,game_pk,game_date,season,sport_id,level,league_id,league_name,team_id,team_name,opponent_id,opponent_name,game_type,is_home,day_night,positions_played,r,h,x2b,x3b,hr,rbi,tb,bb,ibb,so,hbp,ab,pa,sb,cs,gidp,np,lob,sh,sf
0,680474,Max Schuemann,822907,2026-04-29,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,False,day,LF,0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,13,0,0,0
1,680474,Max Schuemann,823555,2026-05-03,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,RF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,680474,Max Schuemann,823552,2026-05-04,2026,1,MLB,103,American League,147,New York Yankees,110,Baltimore Orioles,R,True,day,RF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,680474,Max Schuemann,823551,2026-05-07,2026,1,MLB,103,American League,147,New York Yankees,140,Texas Rangers,R,True,day,"SS,RF",0,1,1,0,0,1,2,0,0,1,0,4,4,0,0,0,16,4,0,0
4,680474,Max Schuemann,823792,2026-05-09,2026,1,MLB,103,American League,147,New York Yankees,158,Milwaukee Brewers,R,False,day,"PR,LF",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
def transform_hitters(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame[cols]
    frame = frame.rename(columns=mapped_cols)
    frame['positions_played'] = frame['positions_played'].apply(lambda lst: ','.join(p['abbreviation'] for p in lst) if lst else '')
    frame['game_date'] = pd.to_datetime(frame['game_date'], format='%Y-%m-%d')
    frame['season'] = frame['season'].astype(int)
    return frame

In [13]:
date = "2026-06-02" # Most recent data pull
prefix = f"raw/game_logs/{date}/"

keys = []
paginator = s3.get_paginator("list_objects_v2")
for page in paginator.paginate(Bucket=BUCKET, Prefix=prefix):
    for obj in page.get("Contents", []):
        if obj["Key"].endswith("_hitting.json"):
            keys.append(obj["Key"])

In [14]:
frames = []
for key in keys:
    obj = s3.get_object(Bucket=BUCKET, Key=key)
    data = json.loads(obj["Body"].read())
    if not data.get('stats') or not data['stats'][0].get('splits'):
        continue
    splits = data['stats'][0]['splits']
    frame = pd.json_normalize(splits)
    frame = transform_hitters(frame)
    frames.append(frame)
    print(key)

raw/game_logs/2026-06-02/player_502671_hitting.json
raw/game_logs/2026-06-02/player_592450_hitting.json
raw/game_logs/2026-06-02/player_641355_hitting.json
raw/game_logs/2026-06-02/player_641555_hitting.json
raw/game_logs/2026-06-02/player_641857_hitting.json
raw/game_logs/2026-06-02/player_663757_hitting.json
raw/game_logs/2026-06-02/player_665862_hitting.json
raw/game_logs/2026-06-02/player_669224_hitting.json
raw/game_logs/2026-06-02/player_676609_hitting.json
raw/game_logs/2026-06-02/player_680474_hitting.json
raw/game_logs/2026-06-02/player_682987_hitting.json
raw/game_logs/2026-06-02/player_683011_hitting.json
raw/game_logs/2026-06-02/player_700250_hitting.json

In [15]:
df = pd.concat(frames, ignore_index=True)
df.shape
df['player_name'].nunique()

13

In [16]:
df.shape

(522, 37)

In [17]:
out_key = "transformed/parquet/game_logs/hitting/date=2026-06-02/game_logs_hitting.parquet"
buf = io.BytesIO()
df.to_parquet(buf, engine="pyarrow", index=False)
buf.seek(0)
s3.put_object(Bucket=BUCKET, Key=out_key, Body=buf.getvalue())

{'ResponseMetadata': {'RequestId': 'MA1MTRPEPXFDV0M9',
  'HostId': 'oAPplji7wEaOQT/6zafDBuDbJSrI21gheh7AR/hGkzEira6x/Wqh8z5a7WfXodqRq8dZ2Wl9tKSC89r2FGjDYm8CnyMDb/EN',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'oAPplji7wEaOQT/6zafDBuDbJSrI21gheh7AR/hGkzEira6x/Wqh8z5a7WfXodqRq8dZ2Wl9tKSC89r2FGjDYm8CnyMDb/EN',
   'x-amz-request-id': 'MA1MTRPEPXFDV0M9',
   'date': 'Wed, 03 Jun 2026 15:11:44 GMT',
   'x-amz-server-side-encryption': 'AES256',
   'etag': '"3de5c556043ec0bca5278d5a8e2e936b"',
   'x-amz-checksum-crc32': 'uwrYzw==',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'ETag': '"3de5c556043ec0bca5278d5a8e2e936b"',
 'ChecksumCRC32': 'uwrYzw==',
 'ChecksumType': 'FULL_OBJECT',
 'ServerSideEncryption': 'AES256'}

## Pitchers

In [19]:
# grab one file to start
test_pitcher_key = "raw/game_logs/2026-06-02/player_518585_pitching.json"
obj = s3.get_object(Bucket=BUCKET, Key=test_pitcher_key)
data = json.loads(obj["Body"].read())

In [20]:
splits = data['stats'][0]['splits']
df = pd.json_normalize(splits)
df.columns

Index(['season', 'date', 'gameType', 'isHome', 'isWin', 'stat.summary',
       'stat.gamesPlayed', 'stat.gamesStarted', 'stat.flyOuts',
       'stat.groundOuts', 'stat.airOuts', 'stat.runs', 'stat.doubles',
       'stat.triples', 'stat.homeRuns', 'stat.strikeOuts', 'stat.baseOnBalls',
       'stat.intentionalWalks', 'stat.hits', 'stat.hitByPitch', 'stat.avg',
       'stat.atBats', 'stat.obp', 'stat.slg', 'stat.ops',
       'stat.caughtStealing', 'stat.stolenBases', 'stat.stolenBasePercentage',
       'stat.caughtStealingPercentage', 'stat.groundIntoDoublePlay',
       'stat.numberOfPitches', 'stat.era', 'stat.inningsPitched', 'stat.wins',
       'stat.losses', 'stat.saves', 'stat.saveOpportunities', 'stat.holds',
       'stat.blownSaves', 'stat.earnedRuns', 'stat.whip', 'stat.battersFaced',
       'stat.outs', 'stat.gamesPitched', 'stat.completeGames', 'stat.shutouts',
       'stat.strikes', 'stat.strikePercentage', 'stat.hitBatsmen',
       'stat.balks', 'stat.wildPitches', 'stat.pickoffs', 'stat.totalBases',
       'stat.groundOutsToAirouts', 'stat.winPercentage',
       'stat.pitchesPerInning', 'stat.gamesFinished',
       'stat.strikeoutWalkRatio', 'stat.strikeoutsPer9Inn',
       'stat.walksPer9Inn', 'stat.hitsPer9Inn', 'stat.runsScoredPer9',
       'stat.homeRunsPer9', 'stat.inheritedRunners',
       'stat.inheritedRunnersScored', 'stat.catchersInterference',
       'stat.sacBunts', 'stat.sacFlies', 'team.id', 'team.name', 'team.link',
       'player.id', 'player.fullName', 'player.link', 'league.id',
       'league.name', 'league.link', 'sport.id', 'sport.link',
       'sport.abbreviation', 'opponent.id', 'opponent.name', 'opponent.link',
       'game.gamePk', 'game.link', 'game.content.link', 'game.gameNumber',
       'game.dayNight'],
      dtype='str')

In [21]:
cols = [
    # identity / keys
    'player.id', 'player.fullName', 'game.gamePk', 'date', 'season',
    # dimensions
    'sport.id', 'sport.abbreviation', 'league.id', 'league.name',
    'team.id', 'team.name', 'opponent.id', 'opponent.name',
    'gameType', 'isHome', 'game.dayNight',
    # stats
    'stat.gamesStarted', 'stat.runs', 'stat.doubles',
    'stat.triples', 'stat.homeRuns', 'stat.strikeOuts', 'stat.baseOnBalls',
    'stat.intentionalWalks', 'stat.hits', 'stat.atBats',
    'stat.caughtStealing', 'stat.stolenBases', 'stat.groundIntoDoublePlay',
    'stat.numberOfPitches', 'stat.wins', 
    'stat.losses', 'stat.saves', 'stat.saveOpportunities', 'stat.holds',
    'stat.blownSaves', 'stat.earnedRuns', 'stat.battersFaced',
    'stat.outs', 'stat.completeGames', 'stat.shutouts',
    'stat.strikes', 'stat.hitBatsmen',
    'stat.balks', 'stat.wildPitches', 'stat.pickoffs', 'stat.totalBases', 
    'stat.gamesFinished', 'stat.inheritedRunners',
    'stat.inheritedRunnersScored',
    'stat.sacBunts', 'stat.sacFlies',
    ]

df = df[cols]
df.head(1)

,player.id,player.fullName,game.gamePk,date,season,sport.id,sport.abbreviation,league.id,league.name,team.id,team.name,opponent.id,opponent.name,gameType,isHome,game.dayNight,stat.gamesStarted,stat.runs,stat.doubles,stat.triples,stat.homeRuns,stat.strikeOuts,stat.baseOnBalls,stat.intentionalWalks,stat.hits,stat.atBats,stat.caughtStealing,stat.stolenBases,stat.groundIntoDoublePlay,stat.numberOfPitches,stat.wins,stat.losses,stat.saves,stat.saveOpportunities,stat.holds,stat.blownSaves,stat.earnedRuns,stat.battersFaced,stat.outs,stat.completeGames,stat.shutouts,stat.strikes,stat.hitBatsmen,stat.balks,stat.wildPitches,stat.pickoffs,stat.totalBases,stat.gamesFinished,stat.inheritedRunners,stat.inheritedRunnersScored,stat.sacBunts,stat.sacFlies
0,518585,Fernando Cruz,823243,2026-03-27,2026,1,MLB,103,American League,147,New York Yankees,137,San Francisco Giants,R,False,day,0,0,0,0,0,0,1,0,0,2,0,0,0,10,0,0,0,0,1,0,0,3,2,0,0,5,0,0,0,0,0,0,0,0,0,0

In [ ]:
mapped_cols = {
    'player.id': 'player_id',
    'player.fullName': 'player_name',
    'game.gamePk': 'game_pk',
    'date': 'game_date',
    'sport.id': 'sport_id',
    'sport.abbreviation': 'level',
    'league.id': 'league_id',
    'league.name': 'league_name',
    'team.id': 'team_id',
    'team.name': 'team_name',
    'opponent.id': 'opponent_id',
    'opponent.name': 'opponent_name',
    'gameType': 'game_type',
    'isHome': 'is_home',
    'game.dayNight': 'day_night',
    'stat.gamesStarted': 'gs',
    'stat.runs': 'r',
    'stat.doubles': 'x2b',
    'stat.triples': 'x3b',
    'stat.homeRuns': 'hr',
    'stat.strikeOuts': 'so',
    'stat.baseOnBalls': 'bb',
    'stat.intentionalWalks': 'ibb',
    'stat.hits': 'h',
    'stat.atBats': 'ab',
    'stat.caughtStealing': 'cs',
    'stat.stolenBases': 'sb',
    'stat.groundIntoDoublePlay': 'gidp',
    'stat.numberOfPitches': 'np',
    'stat.wins': 'w',
    'stat.losses': 'l',
    'stat.saves': 'sv',
    'stat.saveOpportunities': 'svo',
    'stat.holds': 'hld',
    'stat.blownSaves': 'bs',
    'stat.earnedRuns': 'er',
    'stat.battersFaced': 'bf',
    'stat.outs': 'outs',
    'stat.completeGames': 'cg',
    'stat.shutouts': 'sho',
    'stat.strikes': 'strikes',
    'stat.hitBatsmen': 'hbp',
    'stat.balks': 'balks',
    'stat.wildPitches': 'wp',
    'stat.pickoffs': 'pickoffs',
    'stat.totalBases': 'tb',
    'stat.gamesFinished': 'gf',
    'stat.inheritedRunners': 'ir',
    'stat.inheritedRunnersScored': 'irs',
    'stat.sacBunts': 'sh',
    'stat.sacFlies': 'sf',
}